<a href="https://colab.research.google.com/github/BhojRajBist/BhojRajBist/blob/main/DSA_from_beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
rainfall = [12.5, 15.8, 0, 20.3, 5.5]


In [ ]:
import numpy as np

rainfall_array = np.array(rainfall)


In [ ]:
# 1. Print the maximum rainfall
max_rainfall = np.max(rainfall_array)
print("Maximum rainfall:", max_rainfall)

# 2. Print average rainfall
avg_rainfall = np.mean(rainfall_array)
print("Average rainfall:", avg_rainfall)

# 3. Remove all days with zero rainfall (filtering)
non_zero_rainfall = rainfall_array[rainfall_array != 0]
print("Rainfall without zeros:", non_zero_rainfall)

Maximum rainfall: 20.3
Average rainfall: 10.82
Rainfall without zeros: [12.5 15.8 20.3  5.5]


In [ ]:

rainfall_array = rainfall_array * 10  # Multiply all elements by 10


In [ ]:
greater_than_10 = rainfall_array > 10
print("Rainfall > 10mm:", rainfall_array[greater_than_10])

Rainfall > 10mm: [1250. 1580. 2030.  550.]


In [ ]:
non_zero_rainfall = rainfall_array[rainfall_array != 0]
mean_non_zero = non_zero_rainfall.mean()
rainfall_array[rainfall_array == 0] = mean_non_zero
print("After replacing zeros with mean:", rainfall_array)

After replacing zeros with mean: [1250.  1580.  1352.5 2030.   550. ]


In [ ]:
scaled_rainfall = rainfall_array * 1.5
print("Scaled rainfall:", scaled_rainfall)

Scaled rainfall: [1875.   2370.   2028.75 3045.    825.  ]


In [ ]:
import numpy as np

# Create a 5x5 grid of random rainfall values between 0 and 100
rainfall_grid = np.random.uniform(0, 100, (5, 5))
print("Rainfall Grid:\n", rainfall_grid)

# Find the maximum rainfall in the grid
max_rainfall = np.max(rainfall_grid)
print("Maximum rainfall in the grid:", max_rainfall)


Rainfall Grid:
 [[93.71427103 84.35222234 79.77308028 25.39005512 89.08298553]
 [61.93097571 50.11114226 24.77039496 35.50118639 83.49069242]
 [51.44115403 70.88536869 10.28776086 73.24557966 99.49097331]
 [53.00169155 98.98364295 84.75747141 65.17587333 87.68957937]
 [94.81274603 86.30916954 17.52081016 16.09763406  1.19170517]]
Maximum rainfall in the grid: 99.49097330650035


In [1]:


import numpy as np
# Sum of all rainfall in the grid
total_rainfall = np.sum(rainfall_grid)
print("Total rainfall in the grid:", total_rainfall)

# Calculate the average rainfall per column
avg_rainfall_per_column = np.mean(rainfall_grid, axis=0)
print("Average rainfall per column:", avg_rainfall_per_column)

# Select rows where the first column has rainfall greater than 50
high_rainfall_rows = rainfall_grid[rainfall_grid[:, 0] > 50]
print("Rows with first column rainfall > 50:\n", high_rainfall_rows)

# Replace values less than 20 with 0
rainfall_grid[rainfall_grid < 20] = 0
print("Grid after replacing < 20 with 0:\n", rainfall_grid)

# Reshape the grid into a 1D array
flattened_grid = rainfall_grid.flatten()
print("Flattened grid:", flattened_grid)

# Sort the flattened array in ascending order
sorted_rainfall = np.sort(flattened_grid)
print("Sorted flattened rainfall:", sorted_rainfall)

# Find the indices of the sorted values
sorted_indices = np.argsort(flattened_grid)
print("Indices of sorted flattened rainfall:", sorted_indices)

NameError: name 'rainfall_grid' is not defined