<a href="https://colab.research.google.com/github/BhojRajBist/BhojRajBist/blob/main/rasterio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Rasterio Basics

`rasterio` is a Python library for reading and writing raster geospatial data. It's built on top of GDAL and provides a more Pythonic interface for working with raster files.

Here are some basic operations you can perform with `rasterio`:

1.  **Installation**: Install the library.
2.  **Opening and Reading Raster Files**: How to open a raster file and access its metadata and data.
3.  **Writing Raster Files**: How to create and write a new raster file.

In [1]:
%pip install rasterio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 60.7 MB/s eta 0:00:00


### Opening and Reading Raster Files

To open a raster file, you use `rasterio.open()`. This returns a `DatasetReader` object, which you can use to access various properties of the raster, such as its width, height, coordinate reference system (CRS), transform, and band data.

In [2]:
import rasterio
import numpy as np

# Create a dummy raster file for demonstration
# In a real scenario, you would replace this with your actual raster file path
height, width = 100, 100
count = 1 # Number of bands
dtype = rasterio.uint8
crs = 'EPSG:4326'
transform = rasterio.transform.from_origin(0, 90, 1, 1) # Simple identity transform

# Generate some dummy data
data = np.random.randint(0, 256, size=(count, height, width), dtype=dtype)

# Define the file path
dummy_raster_path = '/tmp/dummy_raster.tif'

# Write the dummy raster file
with rasterio.open(
    dummy_raster_path,
    'w',
    driver='GTiff',
    height=height,
    width=width,
    count=count,
    dtype=dtype,
    crs=crs,
    transform=transform
) as dst:
    dst.write(data)

print(f"Dummy raster file created at: {dummy_raster_path}")

# Open the raster file
with rasterio.open(dummy_raster_path) as src:
    print(f"Driver: {src.driver}")
    print(f"Width: {src.width}")
    print(f"Height: {src.height}")
    print(f"Count (number of bands): {src.count}")
    print(f"CRS: {src.crs}")
    print(f"Transform: {src.transform}")

    # Read a band (e.g., the first band)
    band1 = src.read(1)
    print(f"Band 1 data shape: {band1.shape}")
    print(f"Band 1 data type: {band1.dtype}")
    print(f"Band 1 data (first 5x5 pixels):\n{band1[:5, :5]}")

Dummy raster file created at: /tmp/dummy_raster.tif
Driver: GTiff
Width: 100
Height: 100
Count (number of bands): 1
CRS: EPSG:4326
Transform: | 1.00, 0.00, 0.00|
| 0.00,-1.00, 90.00|
| 0.00, 0.00, 1.00|
Band 1 data shape: (100, 100)
Band 1 data type: uint8
Band 1 data (first 5x5 pixels):
[[250  96  96  90 127]
 [ 87 162  66 122 171]
 [ 34 235 185   2 206]
 [210 202  18 169  40]
 [ 24 149  95 186 136]]


### Writing Raster Files

To write a new raster file, you also use `rasterio.open()`, but with the mode set to 'w'. You need to provide the file path and several metadata parameters like driver, width, height, count, dtype, crs, and transform.

In [3]:
# Create some dummy data for a new raster
new_height, new_width = 50, 50
new_count = 1
new_dtype = rasterio.float32
new_crs = 'EPSG:32632' # Example of a different CRS
new_transform = rasterio.transform.from_origin(100000, 0, 10, 10) # Example of a different transform

new_data = np.random.rand(new_count, new_height, new_width).astype(new_dtype)

# Define the file path for the new raster
new_raster_path = '/tmp/new_raster.tif'

# Write the new raster file
with rasterio.open(
    new_raster_path,
    'w',
    driver='GTiff',
    height=new_height,
    width=new_width,
    count=new_count,
    dtype=new_dtype,
    crs=new_crs,
    transform=new_transform
) as dst:
    dst.write(new_data)

print(f"New raster file created at: {new_raster_path}")

# Verify the new raster file
with rasterio.open(new_raster_path) as src:
    print(f"Driver: {src.driver}")
    print(f"Width: {src.width}")
    print(f"Height: {src.height}")
    print(f"CRS: {src.crs}")

New raster file created at: /tmp/new_raster.tif
Driver: GTiff
Width: 50
Height: 50
CRS: EPSG:32632
